create_model:
    data_path: 'data/BonIver.txt'
    model_name : '124M' 
    steps : 70 
    restore_from : 'fresh' 
    run_name : 'run1' 
    print_every : 5 
    sample_every : 10 
    save_every : 50
